/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Utilities.SingletonConnexion;
import controller.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import javax.swing.JButton;

/**
 *
 * @author faiza
 */
public class ViewMenu extends javax.swing.JFrame {

    static Connection Con=SingletonConnexion.getCon();
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAffProjet = new javax.swing.JButton();
        jButtonProjet = new javax.swing.JButton();
        jButtonTache = new javax.swing.JButton();
        jButtonPresonnel = new javax.swing.JButton();
        jButtonEquipe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SYSTEME DE GESTION ET SUIVIE DES TÂCHES DU PERSONNEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 730, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("GSTP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 120, 40));

        jButtonAffProjet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAffProjet.setText("Gestion des Affections des projets");
        jButtonAffProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAffProjetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAffProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 250, 30));

        jButtonProjet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonProjet.setText("Gestion des Projets");
        jButtonProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 250, 30));

        jButtonTache.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTache.setText("Gestion des tâches");
        jButtonTache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTacheActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTache, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 250, 30));

        jButtonPresonnel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPresonnel.setText("Gestion du personnel");
        jButtonPresonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPresonnelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPresonnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 250, 30));

        jButtonEquipe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonEquipe.setText("Gestion des équipes");
        jButtonEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEquipeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEquipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 250, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gestion-financiere-gain-pmu.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjetActionPerformed
        close();
        ViewProjet p=new ViewProjet();
        ControllerProjet c=new ControllerProjet(p);
        c.initialiserTableau();
        p.setVisible(true);
        
    }//GEN-LAST:event_jButtonProjetActionPerformed

    private void jButtonTacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTacheActionPerformed
        close();
        ViewTache p=new ViewTache();
        ControllerTache c=new ControllerTache(p);
        c.initialiserTableau();
        p.setVisible(true);
    }//GEN-LAST:event_jButtonTacheActionPerformed

    private void jButtonPresonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPresonnelActionPerformed
       
    }//GEN-LAST:event_jButtonPresonnelActionPerformed

    private void jButtonEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEquipeActionPerformed
        close();
        ViewEquipe p=new ViewEquipe();
        ControllerEquipe c=new ControllerEquipe(p);
        c.initialiserTableau();
        p.setVisible(true);
    }//GEN-LAST:event_jButtonEquipeActionPerformed

   

    private void jButtonAffProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAffProjetActionPerformed
        close();
        ViewProjetRessource p=new ViewProjetRessource();
        ControllerProjetRessource c=new ControllerProjetRessource(p);
        c.initialiserTableau();
        p.setVisible(true);
    }//GEN-LAST:event_jButtonAffProjetActionPerformed
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
     public JButton getjButtonPresonnel() {
        return jButtonPresonnel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewMenu v=new ViewMenu();
                ControllerMenu c=new ControllerMenu(v);
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAffProjet;
    private javax.swing.JButton jButtonEquipe;
    private javax.swing.JButton jButtonPresonnel;
    private javax.swing.JButton jButtonProjet;
    private javax.swing.JButton jButtonTache;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
