/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.ControllerTache;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author faiza
 */
public class ViewTache extends javax.swing.JFrame {

    /**
     * Creates new form ViewTache
     */
    public ViewTache() {
        initComponents();
    }

    public JButton getjButtonAjouterTache() {
        return jButtonAjouterTache;
    }

    public JComboBox getjComboIDRT() {
        return jComboIDRT;
    }

    public JComboBox getjComboIdPro() {
        return jComboIdPro;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JDateChooser getjDateChooserDelai() {
        return jDateChooserDelai;
    }

    

    public JTextField getjTextDescTache() {
        return jTextDescTache;
    }

    public JTextField getjTextFontionT() {
        return jTextFontionT;
    }

    public JTextField getjTextIDTache() {
        return jTextIDTache;
    }

    public JTextField getjTextNomT() {
        return jTextNomT;
    }

    public JTextField getjTextNumOrdreT() {
        return jTextNumOrdreT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFontionT = new javax.swing.JTextField();
        jTextDescTache = new javax.swing.JTextField();
        jTextNomT = new javax.swing.JTextField();
        jTextIDTache = new javax.swing.JTextField();
        jTextNumOrdreT = new javax.swing.JTextField();
        jComboIDRT = new javax.swing.JComboBox();
        jComboIdPro = new javax.swing.JComboBox();
        jButtonAjouterTache = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooserDelai = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Gestion des tâches");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 350, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Id Tâche :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Nom du tâche :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Déscription de tâche :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Délai du tâche :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Fonction du ressource dans cette tâche :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Numéro d'ordre du ressource dans la tâche :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 280, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Id du projet de cette tâche :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Id de la ressource affecté à cette tâche :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 290, 30));
        getContentPane().add(jTextFontionT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 150, 30));
        getContentPane().add(jTextDescTache, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 150, 30));
        getContentPane().add(jTextNomT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 150, 30));
        getContentPane().add(jTextIDTache, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 150, 30));
        getContentPane().add(jTextNumOrdreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 150, 30));

        getContentPane().add(jComboIDRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 150, 30));

        getContentPane().add(jComboIdPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 150, 30));

        jButtonAjouterTache.setText("Ajouter Nvlle Tâche");
        getContentPane().add(jButtonAjouterTache, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, -1, -1));

        jButton2.setText("Modifier Tâche");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 580, 410));

        jDateChooserDelai.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooserDelai, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 150, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gestion-financiere-gain-pmu.jpg"))); // NOI18N
        jLabel10.setText("jLabel5");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewTache v=new ViewTache();
                ControllerTache c=new ControllerTache(v);
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAjouterTache;
    private javax.swing.JComboBox jComboIDRT;
    private javax.swing.JComboBox jComboIdPro;
    private com.toedter.calendar.JDateChooser jDateChooserDelai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescTache;
    private javax.swing.JTextField jTextFontionT;
    private javax.swing.JTextField jTextIDTache;
    private javax.swing.JTextField jTextNomT;
    private javax.swing.JTextField jTextNumOrdreT;
    // End of variables declaration//GEN-END:variables
}
